# See https://cloud.google.com/cloud-build/docs/build-config
options:
  substitution_option: ALLOW_LOOSE
  machineType: E2_HIGHCPU_8
steps:
- name: gcr.io/k8s-testimages/krte:latest-main
  entrypoint: make
  args: ['-C', 'images/local-path-provisioner', 'push']
